# This Dockerfile builds the API only.

FROM python:3.9
WORKDIR /app

COPY api/requirements.txt api/api.py api/.flaskenv ./

WORKDIR usr/local/bin/python
RUN pip install --upgrade pip

WORKDIR /app
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 8000
CMD ["gunicorn", "-b", ":8000", "api:app"]
